# Site settings
title: rky
SEOTitle: rky的博客 | Study Boy
header-img: img/post-bg-desk.jpg
email: javalgo@outlook.com
description: "Every failure is leading towards success."
keyword: "rky, rky Blog, rky的博客, Study Boy"
url: "http://rky.github.io"
baseurl: ""
github_repo: "https://github.com/rky/rky.github.io.git"

# Sidebar settings
sidebar: true
sidebar-about-description: "Every failure is leading towards success."
sidebar-avatar: /img/rky.jpg

# SNS settings
RSS: false
# weibo_username: rky
bilibili_username: rky

# Build settings
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true

# Gems
gems: [jekyll-paginate]

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# 评论系统
# Gitalk
gitalk:
  enable: true
  clientID: Ov23liE5acY962nbKVnY
  clientSecret: a246c9d3011f3aaab9669e95c82bb9a1d24730e9
  repo: rky-ww.github.io
  owner: rky-ww
  admin: rky-ww
  distractionFreeMode: true

# 统计
# Analytics settings
# Baidu Analytics
ba_track_id: 8c6485a05301de4a4d7b307903a51619

# Google Analytics
# ga_track_id: 'UA-90855596-1'
# ga_domain: rky.top

# Featured Tags
featured-tags: true
featured-condition-size: 1

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
friends: [
    {
        title: "世界上最帅的男人",
        href: "http://rky-ww.github.io"
    }
]